version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  analyze:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: npm i
      - run: npm audit

workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test


  